# main text of home
name: Zekai Chen
bio: Master of Statistics at GWU who is focusing on machine learning and deep learning

# twitter summary info
description: A blog about myself and technology

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://zekaichen.github.io/CV.pdf

url: https://zekaichen.github.io
# your url: http://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: zekai.chen.58
twitter: zech_chan
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: zekai-chen-0239b9126
# youtube: myyoutube
# spotify: myspotify
github: zekaichen
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: zech_chan@gwu.edu

authors:
    Zekai Chen:
        name: Zekai Chen
        bio: Master of Statistics at GWU who is looking for a 2018 PhD program in Deeplearning
        external-image: false
        picture: assets/images/profile.jpg
        twitter: zech_chan
    

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
